### ISSUE TITLE
`TypeError` when setting `tag` with `openapi.definition` decorator

### ISSUE THREAD

**Issue by prryplatypus** [sanic-org/sanic-ext#10]
**Describe the bug**
Using the `openapi.definition` decorator to set `tag` raises an exception.

**Screenshots**
![Traceback](https://user-images.githubusercontent.com/25409753/143853044-86adafdc-c6d8-46a3-94b5-bd423fb4d6d8.png)

**To Reproduce**
Use the decorator like so:
```py
@openapi.definition(
    tag="Enterprises",
)
```

**Expected behavior**
The tag is set for the route just like when using `@openapi.tag`.

**Environment (please complete the following information):**
 - Version 21.9.1

**Comment by ChihweiLHBird** [comment]
Fixed via https://github.com/sanic-org/sanic-ext/pull/26
