### ISSUE TITLE
[Bug] [openapi] incorrect behaviour with tortoise-generated pydantic models in documentation

### ISSUE THREAD

**Issue by FlyinPancake** [sanic-org/sanic-ext#103]
**Describe the bug**
Pydantic models have a config member that is obviously not meant included in a request.
As of sanic-ext 22.6.1 the vanilla for manually defined pydantic models it is left out. However when using tortoise-orm's pydantic_model_creator to generate the models, the Config field gets left in and special objects like enums are ignored. 

**Screenshots**
***pydantic_model_creator***
![image](https://user-images.githubusercontent.com/36113055/176842568-e6fbc900-1137-49ec-a1cd-3f86247c24a8.png)

***manual model***
![image](https://user-images.githubusercontent.com/36113055/176843509-21064316-2747-471a-be08-349fcc34e482.png)

**To Reproduce**
***pydantic model creator***
```py
from tortoise.contrib.pydantic import pydantic_model_creator
from models import Customer

model = pydantic_model_creator(Customer, name="customer_in", exclude_readonly=True) 
```

```py
from pydantic import BaseModel
from models import Gender

class CustomerIn(BaseModel):
    name: str
    email: str
    gender: Gender
    ....

model = CustomerIn
```

Attach them both to a route and see the differences.

**Expected behavior**
These two methods need to provide the same outcome.

**Environment (please complete the following information):**
 - OS: Fedora 36
 - Browser  firefox
 - Version 22.6.1

**Additional context**
I'm using the latest stable pydantic and tortoise-orm versions from pypi.

**Comment by FlyinPancake** [comment]
I checked the source and both classes return true for the `is_pydantic` function. 

Let me know how I can help

**Comment by ahopkins** [comment]
The `_is_property` function of this file needs to fix that.

https://github.com/sanic-org/sanic-ext/blob/main/sanic_ext/extensions/openapi/types.py

As for the enum? Well I'd need to see what the generator is actually producing.

**Comment by ahopkins** [comment]
```python
class Gender(Enum):
    MALE = "male"
    FEMALE = "female"


class Customer(BaseModel):
    name: str
    gender: Gender

    class Config:
        ...
```

![image](https://user-images.githubusercontent.com/166269/191464343-ecd39de1-0add-430b-8ce5-3871f140af72.png)

#132 fixes the problem with `Config`. As for enums, that should already be working. Please provide me an example if it is not.
