### ISSUE TITLE
[Bug][openapi] "query" and "path" type parameters can not display properly in the Redoc documentation

### ISSUE THREAD

**Issue by nightstream** [sanic-org/sanic-ext#104]
**Describe the bug**

Sorry my english may be very poor.

I have created an API that accepts both "path" and "query" type parameters, then I added OpenAPI YAML docstring under my API function, but the "query" type parameters were not displayed on the Redoc properly.

I also tried to use the `openapi.parameter`  decorators but didn't work too.

**Screenshots**

![image](https://user-images.githubusercontent.com/11496537/177052568-8485dc27-c3b6-4773-a95d-e40811c82799.png)

**To Reproduce**

this is my route file:

```python3
userbp = Blueprint("usermgr")

# 配置url
userbp.add_route(UserView.as_view(), "/user/<pk:strorempty>")
```

this is my view function's docstring:

```yaml
openapi:
---
summary: 查看用户信息
description: 查看个人信息, 参数id在path中为可选项, 不传id是查询全部用户, 传id查看指定用户的简要信息
operationId: userget
tags:
  - 标签1
  - 标签2
parameters:
  - pkparameter:
    name: pk
    in: path
    description: 用户唯一标识
    required: false
  - queryparameter:
    name: query
    in: query
    description: 用户对象的查询条件。
    schema:
      type: object
      properties:
        username:
          type: string
          description: 用户名, 使用in查询
  - pageparameter:
    name: page
    in: query
    description: 页码, 默认为1
  - limitparameter:
    name: limit
    in: query
    description: 每页数量限制
  - orderparameter:
    name: order
    in: query
    description: 排序规则
responses:
  '200':
    description: 用户信息
    content:
      application/json:
        schema:
          type: object
          properties:
            code:
              type: string
              description: 返回码
            info:
              type: string
              description: 说明
            data:
              type: array
              items:
                type: object
                properties:
                  pk:
                    type: string
                    description: 用户唯一标识
                  username:
                    type: string
                    description: 用户名
                  headimg:
                    type: string
                    description: 用户头像的base64信息
                  level:
                    type: string
                    description: 用户等级
              description: 用户数据
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version   Sanic v22.3.2, sanic-routing==22.3.0, sanic-ext==22.3.2

**Comment by nightstream** [comment]
found this:

https://github.com/sanic-org/sanic-ext/blob/4a6dda9d5c28cfad0988b90a77cb031708a487b3/sanic_ext/extensions/openapi/builders.py#L137-L149

the `_build_merged_dict` function can merge three dicts which names are `default_dict`, `autodoc_dict` and `defined_dict` into one, but when the key is 'parameters' for example, it will just cover the `autodoc_dict`'s value by the `defined_dict`'s value and not merge these values.

**Comment by ahopkins** [comment]
@nightstream Thanks for debugging this! You are right, swapping the order fixes the problem.

```python
@app.get("/<pk:strorempty>")
async def handler(request: Request, pk: Optional[str]):
    """
    openapi:
    ---
    parameters:
      - pk:
        name: pk
        in: path
        required: false
        schema:
            type: string
    """
    return json({"foo": pk})
```

With this line in place, it works as expected
```python
for d in (default_dict, defined_dict, autodoc_dict):
```
![image](https://user-images.githubusercontent.com/166269/183879110-519ce12f-0727-4dea-84f0-175ae4534411.png)
Will get this in the next bug release coming soon.

**Comment by ahopkins** [comment]
There is probably a bigger issue that needs to be addressed in that `Optional[str]` should auto-imply `strorempty`, which should mark it as `required=false` automatically. But a simple fix for now is the order.

**Comment by ahopkins** [comment]
So, upon further thought, this one might need a little more consideration. Because there are certain things that we _DO_ want `defined_dict` to take precedence. Primarily when you do not intend for docstring to be included and want to override the description or summary.

I think we either need another hierarchy to split apart decorators and route definitions, or carve an exception into the priority ordering for this use case.

**Comment by ahopkins** [comment]
Just pushed another change to that PR. This should do the trick and not mess up the existing preferences.
