### ISSUE TITLE
[Bug] Dataclass optional not working in validate query

### ISSUE THREAD

**Issue by weiztech** [sanic-org/sanic-ext#105]
**Describe the bug**
I'm following this tutorial https://sanic.dev/en/plugins/sanic-ext/validation.html#implementation .
with define `dataclass` attribute with optional paramater,
 it will return 400 , if the query params `q` have value ex `q=123123` 
 without value it will work without problem
 
 I also found the same issue when using `pydantic`

**Screenshots**
<img width="1290" alt="Screen Shot 2022-07-05 at 16 21 59" src="https://user-images.githubusercontent.com/7445136/177295868-db8253c4-6fb5-4cc2-90aa-2d82ab465b2e.png">

**To Reproduce**
```
from dataclasses import dataclass, asdict
from typing import Optional

from sanic import Sanic
from sanic.response import json
from sanic_ext import validate


app = Sanic("Sanic-APP")


@dataclass
class SearchParams:
    q: Optional[str] = None


@app.route("/")
@validate(query=SearchParams)
async def handler(request, query: SearchParams):
    return json(asdict(query))

```

**Expected behavior**
when the dataclass attribute is `Optional`, it should not error when we send the query params with value ex `?q=123456`

**Environment (please complete the following information):**
 - OS: Mac Catalina v10.15.7 
 - Browser Chrome
 - Version 103.0.5060.53

**Comment by miss85246** [comment]
@weiztech  Hi, there.
In `GET` method, One parameter can have multiple values, like this:

```url
http://localhost:3000/?q=1&q=2&q=3
```

Most of the time, you don't need to use this feature. one parameter can have only one value.

so, sanic do some process in `RequestParameters` object.

```python
def get(self, name: str, default: Optional[Any] = None) -> Optional[Any]:
    """Return the first value, either the default or actual"""
    return super().get(name, [default])[0]


def getlist(self, name: str, default: Optional[Any] = None) -> Optional[Any]:
    """
    Return the entire list
    """
    return super().get(name, default)
```

```python
print(request.args.get("q"))
# 1

print(request.args.getlist("q"))
# [1, 2, 3]
```

of course, all of these are based on the RequestParameters operations. 

If you print `request.args`, you will see:

```python
print(request.args)
# {'q': ['1', '2']}
# {'q': ['1']}
```

It's a dict whose value is a list.

And In sanic-ext validator, the do_validation function use request.args as the source of data.

you got the validation Error is merited.

Now, you can use dataclass like this to solve this problem temporarily.

```python
@dataclass
class SearchParams:
    q: Optional[List[str]] = None
```

I hope this will help you.

**Comment by weiztech** [comment]
@miss85246 , 

Thanks for let me know the temporary fix. it's really help me 😊😊
Hope the issue will be fixed in future

**Comment by ahopkins** [comment]
So, what makes this one a little different is the `Optional`. If you left that part off it should work. A fix is coming shortly though for the optional.
