### ISSUE TITLE
[Bug] Openapi <str> dynamic path parameters displayed as <object>

### ISSUE THREAD

**Issue by SerGeRybakov** [sanic-org/sanic-ext#108]
**Describe the bug**
Both of the following path setting give the same result on the screenshot
`app.add_route(get_one_point_from_tif, "/tif/<method:str>/<bands:int>/<x:int>/<y:int>", ["GET"])`
`app.add_route(get_one_point_from_tif, "/tif/<method>/<bands:int>/<x:int>/<y:int>", ["GET"])`

**Screenshots**
![image](https://user-images.githubusercontent.com/64586748/181768106-366c0f3a-c957-4478-bd10-d96a1912aa20.png)

**Comment by wfleurant** [comment]
can you share the screen shot function please

**Comment by SerGeRybakov** [comment]
> can you share the function with openapi decorator please

Actually no, because according to sanic-ext docs there's no need to use openapi decorators for this. So I didn't use them.

Sanic == sanic-ext == 22.3.0

At the moment this function has openapi decorators with allowed strings in enums in order to escape and override this bug.
