### ISSUE TITLE
Dependency injection does not support generics

### ISSUE THREAD

**Issue by Le0Developer** [sanic-org/sanic-ext#109]
**Describe the bug**

Dependency injection does not work if the type uses generics.

**To Reproduce**

```py
import typing
from sanic import Sanic, text

T = typing.TypeVar("T")


class Test(typing.Generic[T]):
    test: T


app = Sanic("testapp")
app.ext.dependency(Test())


@app.get("/")
def test(request, test: Test[str]):  # works without [str]
    return text("hi")

```

**Expected behavior**

The dependency should be injected successfully.

**Environment (please complete the following information):**
 - OS: darwin
 - Version sanic==22.6.1 sanic-routing==22.3.0, sanic-ext==22.6.2

**Comment by Le0Developer** [comment]
Issue lies in https://github.com/sanic-org/sanic-ext/blob/main/sanic_ext/bootstrap.py#L144 only getting the class type without any generics. I've looked and not found a way to accurately get the generic type at runtime, so I think this is unfixable and `add_dependency` should be used instead with the concrete type definition.

The following works:
```py
app = Sanic("testapp")
_singleton = Test()
app.ext.dependency(Test[str], lambda *_: _singleton)
```

Maybe it should be added to the docs that `dependency()` does not support generics and `add_dependency` should be used instead?

**Comment by ahopkins** [comment]
Hmm, that may be the case, but does sound like it should be doable. I'll take a look, glad to hear the low-level api works for this though.

**Comment by ahopkins** [comment]
Oh.... I see the issue. Hmm, I am not sure that we can really fix this. It may be just the case that `add_dependency` is the solution.

The way that `dependency` works is by trying to infer the type from the object. Given the instance returned by `Test()`, there is no way for it to know that it is `Test[str]` v `Test[int]`, etc.

This does not feel like a bug so much as a documentation issue.
