### ISSUE TITLE
[Feature Request] Have oauth2-redirect.html built-in for swagger

### ISSUE THREAD

**Issue by BenJeau** [sanic-org/sanic-ext#113]
**Is your feature request related to a problem? Please describe your use case.**
If you specify a security schema using oauth2, when running sanic without any additional config, after authenticating, it will error out saying `GET /docs/oauth2-redirect.html` does not exist.

**Describe the solution you'd like**
We simply need to how this https://github.com/swagger-api/swagger-ui/blob/master/dist/oauth2-redirect.html page for it to work - I'm doing it manually, but think it should be within `sanic_ext`.

We should either just serve the HTML from a CDN, like https://cdn.jsdelivr.net/npm/swagger-ui-dist@4.13.2/oauth2-redirect.html, or have the file directly in the repo.

**Additional context**
Add any other context about the feature request here. This might be which part of source code to modify or some information you think it might help.

**Comment by BenJeau** [comment]
Let me know what you think about this, and I can open a PR with the change

**Comment by ahopkins** [comment]
Completed by #160
