### ISSUE TITLE
Are OpenAPI example objects possible with Sanic's OpenAPI extension?

### ISSUE THREAD

**Issue by christianversloot** [sanic-org/sanic-ext#133]
Hi - I am creating this issue because I have not been able to find an answer to this question in any of the Sanic repositories nor using Sanic docs.

My setup is as follows:
* Sanic based API
* Sanic Extensions based OpenAPI documentation
* Using dataclasses to represent response structure.

By specifying `@openapi.response(...)` decorators using my dataclasses, I am able to specify the response structure of my API. I am now trying to add example objects, too, which should illustrate a specific response example for a specific API route.

I have not been able to identify if this is possible using the decorator or in any other way. I do notice that it is possible to specify example objects per the OpenAPI 3 docs, and thus possibly via the advanced way of specifying Sanic OpenAPI - via the operation level YAML (https://sanic.dev/en/plugins/sanic-ext/openapi/autodoc.html#operation-level-yaml). However, this gets ugly quite soon as some of my JSONs are rather large.

I have looked at the code and see that the `response` decorator supports `kwargs`. Is there any way that such example objects can be specified through these keywords arguments, or in any other way, in such a way that I can just instantiate objects from my dataclasses and pass them to e.g. Sanic's OpenAPI decorators?

That would be really helpful!

Thanks a lot :)

**Comment by ahopkins** [comment]
Good question! Yes, you could write it all yourself. Yes, it could get tedious.

I just added this: https://github.com/sanic-org/sanic-ext/pull/130

That will be merged and released this weekend with 22.9.

**Comment by christianversloot** [comment]
Thanks for your quick response!

As far as I can see, this addition makes possible defining the schema (and hence _structure_ of e.g. your response) in a different way. 

What I am looking for is the addition of example objects that serve as example responses based on the schema, i.e. https://redocly.com/docs/openapi-visual-reference/example/

![image](https://user-images.githubusercontent.com/6450612/191493483-7f352078-ca5c-4952-a8cc-588b031c978b.png)

Is this already possible with OpenAPI definitions?

If we _are_ already talking about the same thing (which I think we're not), please let me know too!

**Comment by morph027** [comment]
Looks like #82 ;)

**Comment by ahopkins** [comment]
That dict will support any OAS schema put into it, so yes: including examples.

**Comment by ahopkins** [comment]
I was playing with this tonight. What do you think of this as an API to support arbitrary data from a dataclass:

```python
@dataclass
class Foobar:
    ident: str = field(metadata={"openapi": {"example": "ABC123"}})
```

I specifically thought to nest the `example` key inside of `openapi` to avoid conflicts. Of course we could ignore that and make it simpler, but that seems not smart.

```py 
ident: str = field(metadata={"example": "ABC123"})
```

Thoughts?

**Comment by morph027** [comment]
Nesting looks good, just in case. If you think of the possibility of a collission, it will happen and you will be mad at yourselfs past version to not include it the first time :grin:

**Comment by ahopkins** [comment]
> Nesting looks good, just in case. If you think of the possibility of a collission, it will happen and you will be mad at yourselfs past version to not include it the first time :grin: 

You are probably right 😆
