### ISSUE TITLE
Question: Best way to extract injection from handler decorator

### ISSUE THREAD

**Issue by BenJeau** [sanic-org/sanic-ext#139]
Sorry this is not a bug or feature, but I was wondering what is the _best_ way to approach this problem.

I have a decorator for my handlers that handles if the request is authenticated and has a token with proper roles, and I have an injection that extracts the authorization bearer token that injects a User.

```py
app.ext.add_dependency(User, get_user)
```

And this is the decorator:

```py
def has_keycloak_roles(roles: set[Role]):
    """ Verfies if request has passed keycloak roles """
    def decorator(f):
        @wraps(f)
        async def decorated_function(request: Request, *args, **kwargs):
            get_user = request.app.ext._injection_registry.get(User) 
            
            if not get_user:
                raise Unauthorized("User needs to be parsed from bearer token", scheme="Bearer")
            
            user = await get_user(request)
            
            if not roles.issubset(user.roles):
                raise Unauthorized(f"User needs the following roles to make the request: {','.join(roles)}", scheme="Bearer")

            retval = f(request, *args, **kwargs)
            if isawaitable(retval):
                retval = await retval
            return retval

        return decorated_function

    return decorator
```

Then I use is like this:

```py
@bp.get("/")
@has_keycloak_roles(roles={"admin"})
async def get_users(request: Request, user: User) -> HTTPResponse:
    ...
```

I'm concerned about the usage of `request.app.ext._injection_registry.get(User)` then calling that function, is there a more elegant way of doing this? Just curious since I'm accessing a `_` variable and it feels weird doing so.

Thanks in advance :)

**Comment by ahopkins** [comment]
I think you are making it harder than it needs to be.

```python
def has_keycloak_roles(roles: set[Role]):
    """Verfies if request has passed keycloak roles"""

    def decorator(f):
        @wraps(f)
        async def decorated_function(
            request: Request, *args, user: User, **kwargs
        ):
            if not roles.issubset(user.roles):
                raise Unauthorized(
                    f"User needs the following roles to make the request: {','.join(roles)}",
                    scheme="Bearer",
                )

            retval = f(request, *args, user=user, **kwargs)
            if isawaitable(retval):
                retval = await retval
            return retval

        return decorated_function

    return decorator
```

**Comment by ahopkins** [comment]
Off topic, but do you actually want it to be `Forbidden`?

**Comment by BenJeau** [comment]
That simplifies it for sure and yes, you're right it should be `Forbidden`, thanks :)

**Comment by BenJeau** [comment]
By extracting user from the params, it would _require_ the handler to have user as a param, right? I'm using the decorator not always with a handler that has user as a param

Would you know of a way to extract it while it not being needed in the handler itself? (from my experimentation, it doesn't seem possible?)

**Comment by ahopkins** [comment]
The question is a matter of knowing whether or not a given handler needs the user injected. This is handled by Sanic Extensions under the hood in another object that is not exposed. So, it's possible, but might not be so nice.

One thing you could do, and I am not sure how much of a pain this might be for your project, is add a definition to the route ctx:

```python
@app.get("/no-user-injection", ctx_suppress_user=True)
async def no_user_injection(request):
    ...
```

And, then inside your decorator:

```python
if not getattr(request.route.ctx, "suppress_user", False):
    kwargs["user"] = user
retval = f(request, *args, **kwargs)
```

The other way you could do it to be more automated without the manual `ctx_` field is by reading the signature yourself in the decorator, and checking to see if the function declares the user. You can try `signature` or `get_type_hints`.

```python
def has_keycloak_roles(roles: set[Role]):
    def decorator(f):
        sig = signature(f)
        ...
```

https://docs.python.org/3/library/inspect.html#inspect.signature
https://docs.python.org/3/library/typing.html#typing.get_type_hints
