### ISSUE TITLE
`@openapi.tag` is ignored when `@openapi.body` is also defined

### ISSUE THREAD

**Issue by prryplatypus** [sanic-org/sanic-ext#142]
**Describe the bug**
When using `@openapi.body` in conjunction with `@openapi.tag`, the defined tag is ignored and the default one is used. Additionally, the body is not displayed.

EDIT: It seems like `@openapi.body` actually causes other decorators to disappear too (I tried with `@openapi.response` too).

**To Reproduce**
Define a handler and use the two decorators mentioned above.

**Expected behavior**
The body format is displayed, and the handler shows up inside its category/tag.

**Environment (please complete the following information):**
 - OS: Win 11
 - Browser: N/A
 - Version [e.g. 0.5.3]: sanic-routing==22.8.0, sanic-testing==22.9.0, sanic-ext==22.9.0

**Code snippet:**
```py
from pydantic import BaseModel
from sanic import Blueprint
from sanic_ext import validate, openapi

bp = Blueprint("api-v1-categories", url_prefix="/categories", version=1)

class CreateCategoryRequest(BaseModel):
    name: str
    display_order: int
    type: int

@openapi.body(CreateCategoryRequest)
@openapi.tag("Categories")
@bp.post("/<category_id:int>")
@validate(json=CreateCategoryRequest)
async def create_category(
    _: Request, body: CreateCategoryRequest, category_id: int
) -> HTTPResponse:
    return json({"foo": "bar"})
```

**UI:**
![imagen](https://user-images.githubusercontent.com/25409753/194639562-552dc846-c9f4-4bd8-bc3a-419de5de1d66.png)

**Comment by scardozos** [comment]
Issue seems to be that the route decorator is not in the outermost layer, as per the official [doc](https://sanic.dev/en/plugins/sanic-ext/openapi/decorators.html#decorators):


> [...] you should make sure that your Sanic route decorator (@app.route, @app.get, etc) is the outermost decorator. 
> That is to say that you should put that first and then one or more of the below decorators after.

By following this, you should be able to see both the correct tag, and the body displayed: 
![image](https://i.ibb.co/HhgFFBv/download.png)

Try using this code:

```python
from pydantic import BaseModel
from sanic import Blueprint
from sanic_ext import validate, openapi

bp = Blueprint("api-v1-categories", url_prefix="/categories", version=1)

class CreateCategoryRequest(BaseModel):
    name: str
    display_order: int
    type: int

@bp.post("/<category_id:int>")
@openapi.body(CreateCategoryRequest)
@openapi.tag("Categories")
@validate(json=CreateCategoryRequest)
async def create_category(
    _: Request, body: CreateCategoryRequest, category_id: int
) -> HTTPResponse:
    return json({"foo": "bar"})
```

**Comment by prryplatypus** [comment]
Me to myself: https://www.youtube.com/watch?v=wKbU8B-QVZk
