### ISSUE TITLE
[Bug] Sanic-ext breaks @app.route(unquote=True)

### ISSUE THREAD

**Issue by xmcp** [sanic-org/sanic-ext#148]
**Describe the bug**
Sanic v21.3 adds [the `unquote` arg in `@app.route`](https://sanic.dev/en/guide/release-notes/v21.3.html#unquote-in-route) to url-decode parameters in routes. But when sanic-ext is loaded, parameters will not be decoded even `unquote` is set.

**Screenshots**
Not related to swagger.

**To Reproduce**
```python
from sanic import Sanic
from sanic.response import text

app = Sanic("test")
#app.config.AUTO_EXTEND = False

@app.route("/<param:str>", methods=["GET"], unquote=True)
async def handler2(request, param):
    return text("OK2 " + param)
```

Then visit `http://127.0.0.1:8000/%E5%95%8A` and find that it returns `OK2 %E5%95%8A`.

**Expected behavior**
The page should return `OK2 啊`.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: not related
 - Version sanic==22.9.0, sanic-ext==22.9.0

**Additional context**
After uncommenting `app.config.AUTO_EXTEND = False` in the script above, sanic works as expected. So this issue is caused by sanic-ext.

**Comment by ChihweiLHBird** [comment]
Thanks for the issue. I am going to investigate it.

**Comment by ChihweiLHBird** [comment]
I found that when the app is extended, for some reason, `unquote(basket['__matches__'][0])` isn't injected into the `find_route` method of the router.
@ahopkins Can you take a look at this issue later? Thanks!

**Comment by xmcp** [comment]
Note: This issue is also reproducible on 21.12.3 which is LTS.

**Comment by ahopkins** [comment]
I see what the issue is. I will get a patch out for 22.12 and 21.12.
