### ISSUE TITLE
[Bug] When Pydantic model refers to another model, swagger errors out and redoc crashes with an error

### ISSUE THREAD

**Issue by BenJeau** [sanic-org/sanic-ext#152]
**Describe the bug**
Invalid openapi spec is created when nested models are present in Pydantic models.

**Screenshots**
Redoc error:
![image](https://user-images.githubusercontent.com/22248828/203652682-b41c0b46-8b6e-493d-a503-0198164cb891.png)

SwaggeUI error:
![image](https://user-images.githubusercontent.com/22248828/203652720-1b57ef7d-9def-484b-b212-dfc3b4d3a1d4.png)

**To Reproduce**
Create an endpoint having a response set by Pydantic
```py
from pydantic import BaseModel
from datetime import datetime

class Alert(BaseModel):
    hit: dict[str, Any]
    last_updated: datetime

class AlertResponse(BaseModel):
    alert: Alert
    rule_id: str

...
@openapi.definition(
    response={'application/json': AlertResponse.schema()}
)
def get_alert(request: Request) -> HTTPResponse:
...
```

The resulting openapi spec is:
```yaml
openapi: 3.0.3
info:
  title: Test API
  version: 0.0.1
paths:
  /api/v1/alerts/{id}:
    get:
      operationId: get~alerts.get_alert
      summary: Get Alert
      tags:
        - alerts
      parameters:
        - name: id
          schema:
            type: string
          required: true
          in: path
      responses:
        default:
          content:
            application/json:
              schema:
                title: AlertResponse
                type: object
                properties:
                  alert:
                    $ref: '#/definitions/Alert'
                  rule_id:
                    title: Rule Id
                    type: string
                required:
                  - alert
                definitions:
                  Alert:
                    title: Alert
                    type: object
                    properties:
                      hit:
                        title: Hit
                        type: object
                      last_updated:
                        title: Last Updated
                        type: string
                        format: date-time
                    required:
                      - hit
                      - last_updated
          description: Default Response
tags:
  - name: alerts
```

And should be

```diff
openapi: 3.0.3
info:
  title: Test API
  version: 0.0.1
+definitions:
+  Alert:
+    title: Alert
+    type: object
+    properties:
+      hit:
+        title: Hit
+        type: object
+      last_updated:
+        title: Last Updated
+        type: string
+        format: date-time
+    required:
+      - hit
+      - last_updated
paths:
  /api/v1/alerts/{id}:
    get:
      operationId: get~alerts.get_alert
      summary: Get Alert
      tags:
        - alerts
      parameters:
        - name: id
          schema:
            type: string
          required: true
          in: path
      responses:
        default:
          content:
            application/json:
              schema:
                title: AlertResponse
                type: object
                properties:
                  alert:
                    $ref: '#/definitions/Alert'
                  rule_id:
                    title: Rule Id
                    type: string
                required:
                  - alert
-               definitions:
-                 Alert:
-                   title: Alert
-                   type: object
-                   properties:
-                     hit:
-                       title: Hit
-                       type: object
-                     last_updated:
-                       title: Last Updated
-                       type: string
-                       format: date-time
-                   required:
-                     - hit
-                     - last_updated
          description: Default Response
tags:
  - name: alerts
```

Putting it in https://editor.swagger.io/ also points out the errors in the spec

**Expected behavior**
For definitions to be placed at the root level of the spec

**Environment (please complete the following information):**
```
Sanic v22.9.1
mode: debug, single worker
server: sanic, HTTP/1.1
python: 3.10.5
platform: Linux-5.4.0-113-generic-x86_64-with-glibc2.28
auto-reload: enabled
packages: sanic-routing==22.8.0, sanic-ext==22.9.1
```

**Additional context**
Digging a bit, it seems like it makes sense this error happens since Pydantic does not have access to the greater openapi spec to add it's global definitions.

Would be great if there's a way to have it fixed without adding any openapi function calls, but I think a possible solution would be to add definitions from Pydantic schema models to the root of the spec via a function call, `openapi.add_definition(Alert)`?

**Comment by ahopkins** [comment]
There are a couple of options:

1. `openapi.component` can be used to add an object. You would need to change how the pydantic schema references it, but that should work
2. Alternatively, `app.ext.openapi.raw` accepts a dictionary where you can add arbitrary data to:
    - info
    - servers
    - paths
    - components
    - security
    - tags
    - externalDocs

Right now it only supports the [fixed root objects](https://swagger.io/specification/#openapi-object). But it does seem reasonable to allow it to also be used for any arbitrary fields since the spec allows it.

I always thought it weird that pydantic opts for the non-standard `'#/definitions/Foo'` instead of `#/components/schemas/Foo`.

You are probably right though that we can use a smoother path and better docs on this. Although, I would not call it a bug.

**Comment by BenJeau** [comment]
Looking at the pydantic docs/repo it seems like they don't fully support Openapi v3 https://github.com/pydantic/pydantic/issues/4621 (which would explain the `#/definitions/Foo`)

I got it working by doing:

```py
from pydantic import BaseModel
from datetime import datetime
from sanic_ext import openapi

class Alert(BaseModel):
    hit: dict[str, Any]
    last_updated: datetime

class AlertResponse(BaseModel):
    alert: Alert
    rule_id: str

openapi.component(Alert)

...
@openapi.definition(
    response={'application/json': AlertResponse.schema(ref_template='#/components/schemas/{model}')}
)
def get_alert(request: Request) -> HTTPResponse:
    ...
````

But this is a bit messy in my opinion, if you have a lot of routes and nested models. I've been thinking of two possible solutions: (for users to not need to do the above):
1. Inspect the resulting openapi spec and bring to the root of the spec any `definitions` key
2. Make response accept a Pydantic model and call schema with the supplied `ref_template` value and verify if the schema depends on other models somehow and add it to the spec as components.

In both cases we'd probably need to raise an error if there's multiple definitions of the same model, if they are not the same.

**Comment by ahopkins** [comment]
Care to propose what that code might look like?

**Comment by ahopkins** [comment]
I have been playing with this. The solution I came up with is really nice and clean an intuitive. My only hesitation is if it is _too_ magical. Meaning, there is no real way to opt out of the behavior and have more manual control.

```py
class Alert(BaseModel):
    hit: dict[str, Any]
    last_updated: datetime


@pydataclass
class AlertResponse:
    alert: Alert
    rule_id: str


@app.get("/")
@openapi.definition(body={"application/json": AlertResponse})
async def handler(request: Request):
    return json({"foo": "bar"})
```

I am wondering if we should opt for something more explicit:

```python
@app.get("/")
@openapi.definition(body={"application/json": to_components(AlertResponse}))
async def handler(request: Request):
    return json({"foo": "bar"})
```

**Comment by ahopkins** [comment]
Ultimately, I think the right decision is to be more explicit.

```python
@app.get("/")
@openapi.definition(body={"application/json": openapi.Component(AlertResponse}))
async def handler(request: Request):
    return json({"foo": "bar"})
```

**Comment by BenJeau** [comment]
Oh nice that is a nice addition, thanks 💯

**Comment by ahopkins** [comment]
I'll try and get some documentation in for it.
