### ISSUE TITLE
Validation query issues with Pydantic Models

### ISSUE THREAD

**Issue by Surphix** [sanic-org/sanic-ext#153]
**Describe the bug**
Pydantic models cannot be properly validated with validate(query=[ModelName]). Due to Request.get_args() leveraging parse_qs to set RequestParameters. Request parameter values are resulting as arrays. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8021518/204042829-f0ed8cd9-d68d-4c13-8050-12729a6e728e.png)
![image](https://user-images.githubusercontent.com/8021518/204042574-fa38b35c-dffa-4258-848d-a9bc6f2f541f.png)
![image](https://user-images.githubusercontent.com/8021518/204043922-9b84b5f4-4315-45c7-a2bb-6a96b3068027.png)

**To Reproduce**
```
from pydantic import BaseModel

class QueryModel(BaseModel):
    example: str

@indicator_bp.route('/test', methods=['GET'])
@validate(query=QueryModel)
async def get_test(request: Request, **kwargs):
    print(kwargs)
    return json({})
```

**Expected behavior**
Query parameters as non collection types when only one parameter key is specified. Resulting in appropriate validations against Pydantic models.

**Environment (please complete the following information):**
- Sanic: v22.9.1
- Python: 3.10.6
 - OS: Ubuntu
 - Platform: 5.15.0-53-generic

**Additional context**

Perhaps leverage the key values to identify if multiples have been provided. Only downside to this is if a list is expected and only 1 param is passed it will result in validation error, but would be much cleaner to handle as part of a custom Pydantic validator.

```
dict(  (k, v if len(v) > 1 else v[0] ) 
for k, v in parse_qs(qs=self.query_string,
                        keep_blank_values=keep_blank_values,
                        strict_parsing=strict_parsing,
                        encoding=encoding,
                        errors=errors,
                       ).items()
)
```

![image](https://user-images.githubusercontent.com/8021518/204051992-ed0e2dcd-5006-4a01-8bd4-377330398385.png)
![image](https://user-images.githubusercontent.com/8021518/204052036-060dbf29-4116-4ef2-8edb-5377190f1d01.png)

**Comment by Surphix** [comment]
The following fix would resolve this issue, https://github.com/sanic-org/sanic-ext/pull/150

**Comment by ChihweiLHBird** [comment]
Duplicated to https://github.com/sanic-org/sanic-ext/issues/147

We may need a further discussion about whether we are going to support non-list parameters from form data. Can you checkout the discussion in `sanic-ext` channel of our discord server? Thanks!
