### ISSUE TITLE
[Bug] Openapi does not show as static name with the word "static" inside.

### ISSUE THREAD

**Issue by i-Ching** [sanic-org/sanic-ext#155]
If I am going to have static() routes, then it is highly suggested that you manually name **without the word "static" inside**.  http://localhost:8000/docs will certainly not document static routes which is registered by any word with "static" inside.

Reference: https://sanic.dev/en/guide/basics/routing.html#static-files

To reproduce the bug, with all lowercase word "static" inside the name:

```py
app.static("/bug1", "/path/to/bug1", name="static1")
app.static("/bug2", "/path/to/bug2", name="bugstatic")
```

But it shows in openapi http://localhost:8000/docs if any uppercase character replaced as below:

```py
app.static("/static1", "/path/to/static1", name="Static")
app.static("/static2", "/path/to/static2", name="statiC")
app.static("/static3", "/path/to/static3", name="stAtic")
```

**Comment by ahopkins** [comment]
:thinking: Do you _want_ the static route to be shown or not?

**Comment by ahopkins** [comment]
To be honest, I think it is more of a bug that the second set show up. #162 removes this and makes it consistent. But it will be consistently hidden.

According to the OAS specs:

> The OpenAPI Specification (OAS) defines a standard, language-agnostic interface to **RESTful APIs** ...

[Source](https://swagger.io/specification/) _emphasis added_

Static files are not restful and do not belong in the OAS docs.
