### ISSUE TITLE
[Bug] OpenAPI swagger.json path is not updated when behind the proxy/APIGW

### ISSUE THREAD

**Issue by saabeilin** [sanic-org/sanic-ext#166]
**Describe the bug**
When running behind the proxy/APIGW, the swagger.json path is not updated and the swagger UI fails

**To Reproduce**
Run the microservice behind the proxy with URL remap like that:
Local: http://yourservice:8080
Global: https://api.yourdomain.io/3.14/yourservice/

**Expected behavior**
Path to the swagger UI is updated so it fetches the API specs from correct path, accessible from outside the API GW.

**Comment by ahopkins** [comment]
Just pushed PR #170 that will solve this when using `SERVER_NAME` to define your external address. LMK if this works for you.

**Comment by saabeilin** [comment]
Thanks a lot @ahopkins - this should work (will test next year:) Should be probably a straightforward workaround to detect it dynamically though? Like `X-Forwarded-For` or whatever?
