### ISSUE TITLE
[Bug] Model with a list field in @openapi decorator causes error.

### ISSUE THREAD

**Issue by loonos** [sanic-org/sanic-ext#175]
**Describe the bug**

Referencing a model with a list type field in an `@openapi` decorator will result in an error.

**Screenshots**

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/40889817/209929374-ec270d01-27c2-4890-b2c2-4f6387ea9170.png">

**To Reproduce**

```python
from typing import List
from pydantic import BaseModel
from sanic import Sanic
from sanic.request import Request
from sanic.response import json
from sanic_ext import openapi


class MyResponse(BaseModel):
    ls: List[int]


app = Sanic("test")


@app.get("/list")
@openapi.definition(response=MyResponse)
async def get_list(_: Request):
    res = {"ls": [1, 2, 3]}
    return json(res)


if __name__ == "__main__":
    app.run(host="0.0.0.0", fast=True, access_log=False)
```

**Expected behavior**

It should works, and finally get a swagger response example value like `{"ls": [0]}`, instead of raising an exception

**Environment (please complete the following information):**
 - OS: macOS
 - ~~Browser [e.g. chrome, firefox]~~
 - Version 22.12.0

**Additional context**
Add any other context about the problem here. This might be how to fix this bug or some hint to fix it.

**Comment by ahopkins** [comment]
You are using pydantic, so you should do this:

```py
@openapi.definition(response=MyResponse.schema())
```

And, since you are on the newest version, to make it even nicer:

```py
@openapi.definition(response=openapi.Component(MyResponse))
```

**Comment by loonos** [comment]
Sorry, I just noticed that the use of the pydantic model as a body/response schema is different than before.
It works well, thanks you!

**Comment by ahopkins** [comment]
@loonos I just pushed a PR that will solve this even if you do not use one of the two solutions I proposed above. Your example works with dataclasses and attrs, but breaks on pydantic because a field was being duplicated. The patch I just push resolves that.

**Comment by FlyinPancake** [comment]
Hi! 

When using nested pydantic models, using `BaseModel.schema()` will cause an incorrect openapi.json to be created.

**Comment by FlyinPancake** [comment]
On my end running this code generates incorrect openapi docs

```py
class User(BaseModel):
    name: str
    age: int


class UserList(BaseModel):
    data: list[User]


@app.get("/")
@openapi.response(200, {"application/json": openapi.Component(UserList)})
async def get_all(request):
    data = [User(name="John", age=20), User(name="Jane", age=21)]

    return json(UserList(data=data))
```
