### ISSUE TITLE
[Bug]Parameter description not included in openapi.json 

### ISSUE THREAD

**Issue by ingarpedersen** [sanic-org/sanic-ext#18]
**Describe the bug**
When using Parameter class to describe a method parameter, the description is not included in the resulting openapi.json

**To reproduce**
The following code tests 3 ways of documenting parameters, the output is almost identical except that test2 is missing the description in the output

```
@app.route('/test1/<val1>')
async def get_test1(request, val1: int):
    """
    openapi:
    ---
    operationId: get.test1
    parameters:
      - name: val1
        in: path
        description: val1 path param
        required: true
        schema:
          type: integer
          format: int32
    """
    return HTTPResponse("ok")

@app.route('/test2/<val1>')
@openapi.parameter(parameter=Parameter(name='val1', schema=int, location='path', description='val1 path param'))
async def get_test2(request, val1: int):
    return HTTPResponse("ok")

@app.route('/test3/<val1>')
@openapi.parameter('val1', description='val1 path param', required=True, schema=int)
async def get_test3(request, val1: int):
    return HTTPResponse("ok")

```

**Expected behavior**
The description part of Parameter should be included in the openapi.json output

**Environment (please complete the following information):**
OS: Windows 10
Python: 3.10
Sanic: 21.9.3
sanic-ext: 21.9.3

**Comment by ChihweiLHBird** [comment]
Fixed in https://github.com/sanic-org/sanic-ext/pull/21
