### ISSUE TITLE
[Bug] Using add_dependency with lambda causes error.

### ISSUE THREAD

**Issue by kinami0331** [sanic-org/sanic-ext#180]
**Describe the bug**

From your [offical document](https://sanic.dev/en/plugins/sanic-ext/injection.html#basic-implementation):

> Lower level: app.ext.add_dependency(...)
> 
> - `type: Type,`: some unique class that will be the type of the oject
> - `constructor: Optional[Callable[..., Any]], `(OPTIONAL): a function that will return that type

If the constructor is a lambda expression, it will cause an error like:

```
Traceback (most recent call last):
  File "/.../lib/python3.10/site-packages/sanic_ext/extensions/injection/constructor.py", line 58, in __call__
    retval = self.func(**args)
TypeError: xxx.<locals>.<lambda>() missing 1 required positional argument: 'yyy'
......
sanic.exceptions.ServerError: Failure to inject dependencies. Make sure that all dependencies for '<lambda>' have been registered.
```

**Screenshots**
No need.

**To Reproduce**

Create a clean test environment:

```
conda create -n pure_test_env python=3.10
conda activate pure_test_env
pip install sanic==22.12.0 sanic-ext==22.12.0
```

Make a small change in the [official example](https://sanic.dev/en/plugins/sanic-ext/injection.html#injecting-services)

```python
from sanic import Sanic, Request
from sanic.response import text

app = Sanic('test')

class FakeConnection:
    async def execute(self, query: str, **arguments):
        return "result"

@app.before_server_start
async def setup_db(app, _):
    app.ctx.db_conn = FakeConnection()
    app.ext.add_dependency(FakeConnection, lambda request: request.app.ctx.db_conn)
    # app.ext.add_dependency(FakeConnection, get_db)

def get_db(request: Request):
    return request.app.ctx.db_conn


@app.get("/")
async def handler(request, conn: FakeConnection):
    response = await conn.execute("...")
    return text(response)

if __name__ == "__main__":
    app.run("0.0.0.0", 5000)

```

**Expected behavior**
Visit localhost:5000 and it will display "result"

**Environment (please complete the following information):**
 - OS: WSL2 Ubuntu-20.04
 - Browser: chrome
 - Version sanic==22.12.0, sanic-ext==22.12.0

**Additional context**
= =

**Comment by ahopkins** [comment]
Being a lambda really has nothing to do with it. The reason that this does not work is that there is no way for it to know that it is expecting a request object. This works in the example because `get_db` is typed with `Request`. If you were to remove that, then it would similarly fail.

Nonetheless, I am adding an alternative pattern for explicitly setting and not using implicit type annotations (which will have the side effect of working for lambdas).

**Comment by kinami0331** [comment]
Thank you for your explanation. I thought it was a bug because I could use lambda expressions like this in version 21.12 (LTS), but I encountered this issue after updating to version 22.12 (LTS). Although I checked the [changelog](https://sanic.readthedocs.io/en/stable/sanic/changelog.html), I might have missed something.

**Comment by ahopkins** [comment]
Sanic Extensions changes don't go there. I am looking at ways to consolidate the organization of the official plugins with the core package.
