### ISSUE TITLE
How to generate openapi specification without running the app?

### ISSUE THREAD

**Issue by iamvishalkhare** [sanic-org/sanic-ext#187]
Need help/suggestion here.
**Use case** - I am trying to use `openapi.json` file during CI pipeline execution. I need to upload it somewhere for further use.
`openapi.json` file is generated at run time and served at `http://0.0.0.0:8090/docs/openapi.json`
I can't run the app during CI pipeline execution due to other dependencies and it seems like a security issue as well.

Can someone please help here on how can I generate `openapi.json` file without actually running the app?
@ahopkins

**Comment by ahopkins** [comment]
Wow, I am not sure this would be easy to do. Sure, it's Python so everything should be possible. But it will take quite a bit of hacking. You would need to instantiate your Sanic app, then attach the blueprint using the blueprint factory which has some startup time methods to build the spec, and ultimate calling:

```python
SpecificationBuilder().build(app).serialize()
```

Sanic is not really meant for offline usage, and the spec builder certainly not.

You are probably _much_ better off running your app in CI with something like this:

```python
from sanic_ext.extensions.openapi.builders import SpecificationBuilder
from ujson import dumps
from pathlib import Path


@app.after_server_start
async def build_spec(app):
    spec = SpecificationBuilder().build(app).serialize()
    Path("/some/location/spec.json").write_text(dumps(spec))
    app.stop()
```

**Comment by iamvishalkhare** [comment]
Thanks @ahopkins.. Life saver :)
