### ISSUE TITLE
[Feature Request] Custom global environment for Jinja2?

### ISSUE THREAD

**Issue by bnoctis** [sanic-org/sanic-ext#195]
**Is your feature request related to a problem? Please describe your use case.**

I have a `config` object that I'd like to pass to all templates.

Currently I have to dig into the source and figure out a workaround like this:

```py
app.ext.environment.globals.update({ 'config': config })
```

**Describe the solution you'd like**

A configuration point like:

```py
from sanic import Sanic

app = Sanic(__name__)
app.config.templating_globals = { 'config': config }
# or
app.config.templating_environment.globals.update({ 'config': config })
```

Will PR myself, but want to ask for input first.

**Comment by ahopkins** [comment]
That is the intended pattern, and not a workaround. It probably could be documented better.
