### ISSUE TITLE
[Bug] `sanic-ext` seems to be instantiated twice when running in debug mode

### ISSUE THREAD

**Issue by prryplatypus** [sanic-org/sanic-ext#25]
**Describe the bug**
When the Sanic app is ran with `debug=True`, it seems like `sanic-ext` is being instantiated twice (maybe due to the reloader?).

**Screenshots**
Debug mode:
![Debug mode on](https://user-images.githubusercontent.com/25409753/146914115-fed0576d-ae22-49a1-8538-66f70ca54f7e.png)

Non-debug mode:
![Debug mode off](https://user-images.githubusercontent.com/25409753/146914205-5de4d75a-e510-485f-a158-f9bf77d070d7.png)

**To Reproduce**
Create a Sanic app, load `sanic-ext` into it and run it using debug mode.

**Expected behavior**
Only one instance of `sanic-ext` is instantiated, or at least it's only logged once

**Environment (please complete the following information):**
 - OS: Windows 10 Home 21H1
 - Browser: N/A
 - Version: Sanic-Ext 21.9.3; Sanic 21.9.3; Routing 0.7.2

**Additional context**
N/A

**Comment by ahopkins** [comment]
Not a bug. It is logging twice because you are extending in the global scope, which is executed once in the main process and once in the worker process. This will behave differently starting in the next release based upon https://github.com/sanic-org/sanic/pull/2308
