### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by Valt25** [sanic-org/sanic-ext#264]
Here is no commits almost for 1 year, issues are answered rarely or by authors themselfs. PR just waits opened.

By the way, sanic main repo is quite active one. And released according to release policy(LTS once per year and intermediate releases). So I want to know, what is the status of this repo?

**Comment by ahopkins** [comment]
Releases tied to main repo.

**Comment by Valt25** [comment]
Ok, I see new release of sanic(24.12) and according to message in discord, sanic-ext would be release next weeks, but still here is no commits(now I see just one since latest(23.12) release)
