### ISSUE TITLE
cdn cdnjs.cloudflare.com 的地址，能否支持自己配置？因为有时候国内第一次访问不通，需要开VPN访问之后缓存一下才行，很不友好啊

### ISSUE THREAD

**Issue by liujunzheng** [sanic-org/sanic-ext#34]
**Describe the bug**
cdn cdnjs.cloudflare.com 的地址，能否支持自己配置？因为有时候国内第一次访问不通，需要开VPN访问之后缓存一下才行，很不友好啊

**Screenshots**
国内第一次访问时，一直pending，场景率很高

**Comment by ahopkins** [comment]
Can you please write your issue in English? While we try to have support in other languages, the development of the project is all in English.

If this is a support question, it should be made in the appropriate language channel in the Discord server.

**Comment by ahopkins** [comment]
If I understand correctly, you can change the CDN by creating a custom HTML template using the configuration options here.

https://sanicframework.org/en/plugins/sanic-ext/openapi/ui.html#config-options

**Comment by ahopkins** [comment]
Templates you can use to start from are here

https://github.com/sanic-org/sanic-ext/tree/main/sanic_ext/extensions/openapi/ui

**Comment by liujunzheng** [comment]
@ahopkins  OK, thank you. After reading the source code, I need to redefine the new swagger HTML to overwrite the default swagger HTML to define the CDN problem. It is also a solution.

**Comment by ahopkins** [comment]
> @ahopkins OK, thank you. After reading the source code, I need to redefine the new swagger HTML to overwrite the default swagger HTML to define the CDN problem. It is also a solution.

Yes
