### ISSUE TITLE
[Bug] Enabling ext breaks static routing

### ISSUE THREAD

**Issue by jackfischer** [sanic-org/sanic-ext#44]
**Describe the bug**

I previously used `app.static` to configure our static files directory. However, after installing ext, GET requests for static files throw 405s and log the following

```
[2022-01-13 12:04:35 -0500] [11337] [DEBUG] Dispatching signal: http.routing.before
[2022-01-13 12:04:35 -0500] - (sanic.access)[INFO][127.0.0.1:60821]: GET http://0.0.0.0:8000/static/pickadate/picker.js  405 777
```

**Screenshots**
N/A

**To Reproduce**

```python
APP = Sanic(...)

static_directory = os.path.abspath("frontend")
APP.static("/static", static_directory)
APP.static("/", os.path.join(static_directory, "index.html"))

APP.extend(config=Config(oas=False)) 
```

**Expected behavior**
GET requests to the `/static/` routes return 200s.

**Environment (please complete the following information):**
 - OS macOS-10.16-x86_64-i386-64bit
 - Browser chrome, firefox
 - Version python==3.9.4, sanic==21.12.1, sanic-routing==0.7.0, sanic-ext==21.12.3
 
Thank you!

**Comment by jackfischer** [comment]
Happy to debug live or provide more details as needed.

**Comment by ahopkins** [comment]
Thanks. I am looking into this.

**Comment by ahopkins** [comment]
@jackfischer I think you will find that the problem resolves itself if you upgrade your `sanic-routing` version to `0.7.2`.

**Comment by jackfischer** [comment]
Success thanks. I notice even 0.7.2 is pretty far behind with the latest release being 21.12.0 but Sanic actually pins the dependency to ~=0.7. TIL this equates to 0.7.*, not 0.7.0.

**Comment by jackfischer** [comment]
Is this worth changing sanic to >=0.7.2,<0.8.0?

**Comment by ahopkins** [comment]
To be honest, it was meant to be released together (which is why I changed sanic-routing to calendar versioning like the main project). However, I made a mistake and did not update the requirement. Since the change also includes a breaking change (deprecation of `string` and `number` in favor of `str` and `float`) it is unfortunately going to have to wait until the March release.
