### ISSUE TITLE
[Bug] Can't use Parameter as an object anymore ?

### ISSUE THREAD

**Issue by koug44** [sanic-org/sanic-ext#53]
**Describe the bug**
In my Sanic application, I declare all my parameters once as they are used accross many endpoints. With last sanic-ext, I have this error:
`AttributeError: module 'sanic_ext.extensions.openapi.openapi' has no attribute 'Parameter'. Did you mean: 'parameter'?`

**To Reproduce**
Simple code to reproduce

```
from sanic import Sanic
from sanic.response import text
from sanic_ext import openapi

app = Sanic("MyHelloWorldApp")
my_parameter = openapi.Parameter()


@app.get("/test1")
@openapi.parameter(my_parameter)
async def test1(request):
    return text("test1")


@app.get("/test2")
@openapi.parameter(my_parameter)
async def test2(request):
    return text("test2")
```

**Additional context**
If this is expected behaviour, please fix the doc also as [this page](https://github.com/sanic-org/sanic-guide/blob/main/src/en/plugins/sanic-ext/openapi/decorators.md) states

> @openapi.parameter(parameter=Parameter("foobar", deprecated=True))

Edit: broken change was introduced w/ 22.1.0

**Comment by ahopkins** [comment]
> Isn't a parameter name required? I'm pretty sure it can't be anonymous.

Yes, `name` is required

```
Traceback (most recent call last):
  File "/tmp/p.py", line 6, in <module>
    my_parameter = openapi.definitions.Parameter()
TypeError: Parameter.__init__() missing 1 required positional argument: 'name'
```

> Simple code to reproduce

I think it is a matter of import paths:

```python
my_parameter = openapi.definitions.Parameter("foo")
```
