### ISSUE TITLE
Running multiple instance of in one heap causes OPENAPI specification to build properly [Bug]

### ISSUE THREAD

**Issue by notzippy** [sanic-org/sanic-ext#54]
**Describe the bug**
Starting two instances of sanic (on different ports) using `create_server` with different routes assigned to them. The API specification will merge all routes together

**Expected behavior**
The specification builder should use the `request.app` to determine which routes are applicable for the specification to be used, and only show those routes.

**Additional context**
As seen [here](https://github.com/sanic-org/sanic-ext/blob/main/sanic_ext/extensions/openapi/blueprint.py#L50) The specification is built from a singleton, if this is in the same heap as the main application then all routes are merged together.

**Comment by ahopkins** [comment]
Yes, this is a known issue and is unlikely to be solved until there is a pretty big refactor. I am working through a couple alternatives to keep backwards compat. Especially in the coming 22.3 where there is an emphasis to easily standup multiple apps on differing ports, this is something that I hope to resolve in the next release.

**Comment by ahopkins** [comment]
A fix for this will be in next week's release.
