### ISSUE TITLE
[Bug] Typing errors when using `openapi` types

### ISSUE THREAD

**Issue by prryplatypus** [sanic-org/sanic-ext#55]
**Describe the bug**
When defining a parameter and using a type such as `openapi.Integer()`, typing checks fail because there's no available overload that matches.

**Screenshots**
![Typing check error](https://i.imgur.com/oponTi6.png)

**To Reproduce**
```py
from sanic_ext import openapi
 
...

@app.route("/")
@openapi.parameter("scope", openapi.Integer())
async def do_stuff(*_, **_):
    ...

```

**Expected behavior**
There's no typing errors.

**Environment (please complete the following information):**
 - OS: Windows 10 Home 21H1
 - Browser: N/A
 - Version: sanic-ext 22.1.2

**Additional context**
N/A

**Comment by ahopkins** [comment]
> I seem to be able to fix this issue by adding default values in the following method overload:

Go for it :muscle:
