### ISSUE TITLE
Swagger UI's stylesheets aren't loaded

### ISSUE THREAD

**Issue by prryplatypus** [sanic-org/sanic-ext#6]
**Describe the bug**
When accessing the `/docs/swagger` route, a blank page is loaded. It seems to be due to the defined stylesheets no longer existing.

**Screenshots**
![Swagger UI blank page](https://user-images.githubusercontent.com/25409753/142840914-2a4149a4-24a1-481a-9699-3438bedc3db0.png)

**To Reproduce**
Load `sanic-ext` into your Sanic app and access the Swagger UI route.

**Expected behavior**
The Swagger UI is displayed.

**Environment (please complete the following information):**
 - OS: Windows 10 Home 21H1
 - Browser Mozilla Firefox
 - Version: 94.0.1 64-bit

**Comment by ahopkins** [comment]
Bummer. Guess we need some new CDN links.

**Comment by ahopkins** [comment]
https://pagecdn.com/public-cdn
It does not show up here anymore. I guess they pulled it :thinking:

**Comment by prryplatypus** [comment]
There’s some Cloudflare hosted ones at https://cdnjs.com/libraries/swagger-ui which look like they could be an option.

**Comment by ahopkins** [comment]
Looks like it is versioned. No `latest`. Which is fine, we will just need to make that a configurable value.
