### ISSUE TITLE
[Bug] Dependency injection not working for websocket handlers

### ISSUE THREAD

**Issue by xmcp** [sanic-org/sanic-ext#61]
**Describe the bug**

Sanic-Ext fails to inject dependencies to `@app.websocket()` handlers.

**Screenshots**

![image](https://user-images.githubusercontent.com/6646473/153877144-16c9f76f-cd1c-4b20-a904-24b50361c923.png)

**To Reproduce**

Try this code:

```python
from sanic import Sanic

app = Sanic('test')

class Foo:
    pass
    
app.ext.add_dependency(Foo, lambda req: None)

@app.websocket('/foo')
async def handler(req, ws, foo: Foo):
    pass
    
app.run(port=4321, debug=True)
```

Visit `http://127.0.0.1:4321/`, then execute `new WebSocket('ws://127.0.0.1:4321/foo')` in browser console.

This error will be thrown:

```
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "C:\Users\xmcp\AppData\Roaming\Python\Python38\site-packages\sanic\app.py", line 1002, in _websocket_handler
    fut = ensure_future(handler(request, ws, *args, **kwargs))
TypeError: handler() missing 1 required positional argument: 'foo'
```

**Expected behavior**

It should not throw an error.

**Environment (please complete the following information):**
- OS: Windows 10 (19044.1466)
- Browser: not related
- Version: sanic 21.12.1, sanic-ext 22.1.2

**Additional context**

Sanic wraps a `functools.partial` to the websocket handler, effectively erasing the type signature of the handler function. Therefore [`sanic_ext.extensions.injection.injector`](https://github.com/sanic-org/sanic-ext/blob/main/sanic_ext/extensions/injection/injector.py#L72) (screenshot below) cannot get its type hint:

![image](https://user-images.githubusercontent.com/6646473/153878115-52f3f08b-872c-416b-a9d2-4edf01125476.png)

**Comment by ahopkins** [comment]
Thanks @xmcp for bringing this up. We will have this fixed in the upcoming release next week.
