### ISSUE TITLE
[Bug] No CORS information if Origin set in the request

### ISSUE THREAD

**Issue by koug44** [sanic-org/sanic-ext#62]
**Describe the bug**
On an OPTIONS HTTP request, no Access-Control headers is returned if the Origin is set 

**To Reproduce**
Simple "Hello world" server from the documentation pages

```
from sanic import Sanic
from sanic.response import text
from sanic_ext import Extend
from sanic_cors import CORS

app = Sanic("MyHelloWorldApp")
Extend(app)
app.config.CORS_ORIGINS = "*"


@app.get("/")
async def hello_world(request):
    return text("Hello, world.")


app.run()
```
On the client side:

```
[dalexandre@dalexandre ~]$ http OPTIONS :8000 Access-Control-Request-Method:GET 
HTTP/1.1 204 No Content
access-control-allow-headers: *
access-control-allow-methods: HEAD,OPTIONS,GET
access-control-allow-origin: *
access-control-max-age: 5
allow: HEAD,GET,OPTIONS
connection: keep-alive
```

```
[dalexandre@dalexandre ~]$ http OPTIONS :8000 Access-Control-Request-Method:GET Origin:test
HTTP/1.1 204 No Content
allow: HEAD,GET,OPTIONS
connection: keep-alive
```

**Expected behavior**
Headers have to be returned wether or not the Origin header is set 

**Environment (please complete the following information):**
Sanic 21.9.3 + Sanic-ext 22.1.2

**Comment by sjsadowski** [comment]
Hi, sanic-ext and sanic-cors have overlapping functionality. Can you remove sanic-cors and re-verify?

**Comment by koug44** [comment]
Sorry, this is a ghost import from several tests. CORS is not called or applied.

Test is the same removing the import

**Comment by sjsadowski** [comment]
using curl, the headers are returned without an issue.
```
curl -v -X OPTIONS -H "Access-Control-Request-Method:GET" -H "Origin: test" http://localhost:8001
*   Trying 127.0.0.1:8001...
* Connected to localhost (127.0.0.1) port 8001 (#0)
> OPTIONS / HTTP/1.1
> Host: localhost:8001
> User-Agent: curl/7.79.1
> Accept: */*
> Access-Control-Request-Method:GET
> Origin: test
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< allow: HEAD,GET,OPTIONS
< connection: keep-alive
< 
* Connection #0 to host localhost left intact
```

**Comment by sjsadowski** [comment]
Confirmed using curl.

```curl -v -X OPTIONS -H "Access-Control-Request-Method:GET" -H "Origin: test" http://localhost:8001
*   Trying 127.0.0.1:8001...
* Connected to localhost (127.0.0.1) port 8001 (#0)
> OPTIONS / HTTP/1.1
> Host: localhost:8001
> User-Agent: curl/7.79.1
> Accept: */*
> Access-Control-Request-Method:GET
> Origin: test
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< allow: HEAD,GET,OPTIONS
< connection: keep-alive
< 
* Connection #0 to host localhost left intact
```

**Comment by jacebrowning** [comment]
When CORS headers are missing, the server logs:

> [INFO] No Access-Control-Request-Method header found on request. CORS headers will not be applied.

Is there a way to **always** send CORS headers?

**Comment by ahopkins** [comment]
@jacebrowning I think you are going about this the wrong way. I would not be setting `CORS_AUTOMATIC_OPTIONS = False`, I do not think that is the functionality you are looking at.

Take a look here about the [Access-Control-Request-Method](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Request-Method) header.

> The Access-Control-Request-Method request header is used by browsers when issuing a [preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request), to let the server know which [HTTP method](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods) will be used when the actual request is made. This header is necessary as the preflight request is always an [OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS) and doesn't use the same method as the actual request.

Your browser will always send this. If you truly want to mimic a preflight request in `curl`, you should include it.

```python
from sanic import Request, Sanic

app = Sanic(__name__)
app.config.CORS_ORIGINS = "*"


@app.get("/")
async def handler(request: Request):
    ...


app.run(port=9999)
```

```
▶ curl localhost:9999 -i -X OPTIONS -H "access-control-request-method: GET" -H "Origin: http://localhost:9999"
HTTP/1.1 204 No Content
allow: GET,HEAD,OPTIONS
access-control-allow-origin: http://localhost:9999
access-control-max-age: 5
access-control-allow-headers: *
access-control-allow-methods: GET,HEAD,OPTIONS
connection: keep-alive

```

**Comment by ahopkins** [comment]
Feel free to carry on the conversation, but I do not see any bug here.

**Comment by koug44** [comment]
@ahopkins  Taking your own CURL request

```
[dalexandre@dalexandre ~]$ curl localhost:9999 -i -X OPTIONS -H "access-control-request-method: GET" -H "Origin: http://localhost:9999"
HTTP/1.1 204 No Content
allow: GET,HEAD,OPTIONS
connection: keep-alive
```
I don't have the headers in the response - it's the reason the issue was created in the first place.
You code snippet does not import sanic-ext in the first place

**Comment by ahopkins** [comment]
> You code snippet does not import sanic-ext in the first place

That is not needed in v21.12

> I don't have the headers in the response

What are your `CORS` settings?

**Comment by koug44** [comment]
The one in the first post. I've just added the 9999 port to answer to your request

**Comment by koug44** [comment]
> What version are you on?

sanic                  21.9.3
sanic-ext              22.1.2

**Comment by ahopkins** [comment]
With Sanic 21.9 you will still need to use `Extend`.

**Comment by koug44** [comment]
Ok. Thanks for that. 

There's no bug with the last version - also the order matters and was the cause for the bug

**Comment by ahopkins** [comment]
> There's no bug with the last version - also the order matters and was the cause for the bug

This is another thing that changes in 21.12. Since there is no need to call `Extend` (you still can if you want, or use `app.extend()`), the order is not a problem.
