### ISSUE TITLE
[Feature Request] Allow choose an HTTP status code to return when raise a validation error

### ISSUE THREAD

**Issue by leotada** [sanic-org/sanic-ext#63]
**Is your feature request related to a problem? Please describe your use case.**
When raise a validation error the HTTP status code 400 is returned always.

**Describe the solution you'd like**
I would like to choose another HTTP status code explicitly when raise an error validation.

**Comment by ahopkins** [comment]
:thinking: This is possible already in a few ways.

**OPTION 1 - custom error handling**

```python
from sanic_ext.exceptions import ValidationError


@app.exception(ValidationError)
async def handle_validation_error(*_):
    return json({"custom": "error"}, status=418)
```

The obvious downside is that you need to create your own message as well. Maybe this is what you want. If not ...

**OPTION 2 - override default status**

Similar to the previous, we create a custom exception handler, but use the default response and just change the status.

```python
@app.exception(ValidationError)
async def handle_validation_error(request: Request, exception):
    response = request.app.error_handler.default(request, exception)
    response.status = 418
    return response
```

**Option 3 - override the exception status**

We can make Option 2 even easier by just overriding the default status on the exception itself:

```python
from sanic_ext.exceptions import ValidationError

ValidationError.status_code = 418
```

---

I think Option 3 achieves the feature you are looking for.
