### ISSUE TITLE
[Feature Request] Render template from string

### ISSUE THREAD

**Issue by azimovMichael** [sanic-org/sanic-ext#72]
**Is your feature request related to a problem? Please describe your use case.**
I'm migrating from Flask to Sanic, and currently I'm using Flask's render_template_string to render a jinja template from a string.
If I understand correctly, Sanic only supports rendering from a file.

**Describe the solution you'd like**
I would like something like this:
```
TEAMPLATE = '''
<!DOCTYPE html>
<html>
<head>
  <style>
    
  </style>
</head>
<body>
  <script>
    
  </script>
</body>
</html>'''

rendered = render_from_string(TEMPLATE, context)
```

**Comment by azimovMichael** [comment]
I will add a PR for this

**Comment by prryplatypus** [comment]
Looking at this... I think all that's necessary is returning the `render_template_string` result with Sanic's `html` method?

```py
from sanic import html

TEMPLATE = '''
<html>
<body>
  ...
</body>
</html>'''

rendered = render_from_string(TEMPLATE, context)

return html(rendered)
```

**Comment by azimovMichael** [comment]
@prryplatypus Not sure I follow. We don't have a `render_from_string` function yet, do we?
It should be similar to the current `render` func, but instead of using `environment.get_template` it should use `environment.from_string`.

Once we'll have this function, I'm not sure why we need to use the `html` instead of returning `HTTPResponse` like the `render` function does

**Comment by ahopkins** [comment]
@azimovMichael You are correct, we do not have that function yet. Your strategy is fine. `html` is just a convenience wrapper. You can just use `HTTPResponse` here as well.

The question that I have is does it make sense to have `render` and `render_from_string`?

Why not something like this:

```python
def render(template_name="", template="", ...):
   if template_name and template:
       raise SomeException

render("my_template_name")
render(template="<html>...")
```

**Comment by azimovMichael** [comment]
@ahopkins I wanted to provide a similar API to what Flask and Jinja itself provide, but sure we can do it in a single function.

**Comment by ahopkins** [comment]
That makes sense. I personally don't like polluting the namespace do much 🤷‍♂️. I don't work on jinja much so this is helpful for me to know.

What if we provide both? I'd even go so far as to make it a keyword only argument on `render`.

**Comment by azimovMichael** [comment]
I'm actually totally fine with providing all in a single function.
Although Jijna does it in 2 functions, I actually prefer it to be in one.
Will do it with a kwarg-only arg.
