### ISSUE TITLE
[Bug] Static and Class methods are added to the example request bodies

### ISSUE THREAD

**Issue by FlyinPancake** [sanic-org/sanic-ext#80]
**Describe the bug**
Class / static methods are included in the example request body.

**To Reproduce**
Create a dataclass add a class/static method to it and set it to a requestbody with `@openapi.body({"application/json": Class})`

**Expected behavior**
We pass an instance of a class so class and static methods should not be in the documentation. 

**Environment (please complete the following information):**
 - OS: Pop OS 22.04
 - Browser curl
 - Version 22.3.1

**Comment by FlyinPancake** [comment]
This issue cause my application not to start under Python 3.10.

**Comment by ahopkins** [comment]
Can you provide a minimal sample code snippet?

**Comment by ahopkins** [comment]
Maybe fixed by #98?

**Comment by ahopkins** [comment]
The `classmethod` will be a nice quick fix that I will get out and released. But `unicode`? :confused: Where is there Python 2 code?! Certainly not from Sanic.

**Comment by FlyinPancake** [comment]
@ahopkins thank you you're a legend
