### ISSUE TITLE
The openapi.definition decorator struggles in a sync context

### ISSUE THREAD

**Issue by sorenrife** [sanic-org/sanic-ext#81]
The [openapi.definition](https://github.com/sanic-org/sanic-ext/blob/2d5e31334565bf8b68d345caf650fab66c0cfd2d/sanic_ext/extensions/openapi/openapi.py#L356) decorator with a [definitions.RequestBody](https://github.com/sanic-org/sanic-ext/blob/2d5e31334565bf8b68d345caf650fab66c0cfd2d/sanic_ext/extensions/openapi/definitions.py#L130]) instance or a non-empty dictionary as the `body` parameter transforms the target function to a coroutine.

For example, in my case, I'm using the decorator in a sync view...

```python
@bp.get("/top/tracks")
@openapi.definition(
    body=oa.RequestBody(serializers.TopTracksRequest, required=True),
    summary="Fetch top tracks",
    response=[
        oa.Response(serializers.TopTracksResponse),
        oa.Response(
            Error, status=404, description="not found. note: sync is required."
        ),
        oa.Response(Error, status=400, description="bad request"),
    ],
)
@authenticate
def fetch_top_tracks(request):
    ...
```

...  that uses the Django ORM to retrieve data, and the only way I have to avoid the Django async safety check is to remove the [definitions.RequestBody](https://github.com/sanic-org/sanic-ext/blob/2d5e31334565bf8b68d345caf650fab66c0cfd2d/sanic_ext/extensions/openapi/definitions.py#L130]) definition as a `body` (or perform an ugly workaround).

![image](https://user-images.githubusercontent.com/55748056/167956731-26d040ac-ebe4-4813-94b5-f5df3002e081.png)
*The code block that triggers the view actually detects the function as a coroutine and calls it as such*

When I remove the `body` parameter, everything works as expected and the view is not triggered as a coroutine.

```python
@bp.get("/top/tracks")
@openapi.definition(
    #body=oa.RequestBody(serializers.TopTracksRequest, required=True),
    summary="Fetch top tracks",
    response=[
        oa.Response(serializers.TopTracksResponse),
        oa.Response(
            Error, status=404, description="not found. note: sync is required."
        ),
        oa.Response(Error, status=400, description="bad request"),
    ],
)
@authenticate
def fetch_top_tracks(request):
    ...
```

I don't know if this behaviour is expected, my guess is that it has something to do with [this check](https://github.com/sanic-org/sanic-ext/blob/2d5e31334565bf8b68d345caf650fab66c0cfd2d/sanic_ext/extensions/openapi/openapi.py#L222). Maybe it could be useful to add fully sync context support to this decorator, or add a flag to avoid explicitly this kind of behaviour.

Maybe it's totally expected, I'm missing the reasoning behind it and the `body` parameter is not expected to be used in a sync context (or needs some unknown -by me- configuration).

Anyway, if the behaviour is expected, I would love to know the reasoning behind it. Also, it could be useful to have it in the documentation since I couldn't understand what was happening easily. If it's already in the documentation and I couldn't find it; Send me a link! 😉

Thanks a lot!
Loving Sanic ❤️

**Comment by ahopkins** [comment]
Thanks, definitely not intended and needs investigation and a fix.

**Comment by ahopkins** [comment]
So, I am not sure that this actually a bug here. This seems to work on both `def` and `async def`.

```python
from sanic import Request, Sanic, json
from sanic_ext import openapi
from sanic_ext.extensions.openapi import definitions as oa

app = Sanic(__name__)


class Error:
    ...


class TopTracksResponse:
    ...


@app.get("/")
@openapi.definition(
    summary="Fetch top tracks",
    response=[
        oa.Response(TopTracksResponse),
        oa.Response(
            Error, status=404, description="not found. note: sync is required."
        ),
        oa.Response(Error, status=400, description="bad request"),
    ],
)
def handler(request: Request):
    return json({"foo": "bar"})
```

Looking at your exception, the problem looks to be something instead that Django has introduced. Namely, if there is a running event loop, then bail out:

![image](https://user-images.githubusercontent.com/166269/168022956-67258e18-d674-4de2-b718-2b758d831acd.png)

It looks like they provide you with an escape hatch though:

```python
from os import environ

environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = True
```

**Comment by ahopkins** [comment]
I'll be honest, this is the first time that I have heard of someone using Django ORM inside Sanic. I am curious to know more about how you wired that up and your experience of and motivation for doing so.

**Comment by sorenrife** [comment]
Yeah, totally, the error itself triggers when Django ORM is run, but the idea is that I was able to use the Django ORM inside my views without any problems because the view wasn't triggered as a coroutine until I add the documentation decorator. So it was fully compatible with the Django ORM in many cases, but the decorator converted the view as a coroutine, so I had to add some patch for Django ORM. Anyway, totally agree that this is not a bug itself, meaning that it's just incompatibility (without a workaround) with some non-async projects.

**Comment by sorenrife** [comment]
> I'll be honest, this is the first time that I have heard of someone using Django ORM inside Sanic. I am curious to know more about how you wired that up and your experience of and motivation for doing so.

The motivation of why we choose Django resides in various ideas; The most important is that Django 4.1 releases in a couple of months with a [new Asynchronous ORM interface](https://docs.djangoproject.com/en/dev/releases/4.1/#asynchronous-orm-interface) so it will be fully compatible with Sanic in every case. So at my opninion we're at doors to have projects with Sanic as REST Framework and Django as ORM, since -as my point of view- Sanic is way better as a REST framework, in many cases. Ours included.
Until now, we were working with Peewee but for many issues with it, we decide it that we're going to play safe and use Django since we had more experience and it's widely recognized. We love Sanic for its Flask-type design, and obviously, the amazing performance it has, so we are excited about this new Django upgrade and loving the idea of working with Sanic and Django comfortably.

![telegram-cloud-photo-size-4-6032961181838325917-y](https://user-images.githubusercontent.com/55748056/168074763-1bdf462c-2bc9-46a7-9ffc-7d4f50153558.jpg)

For now, until this update comes, we're basically mantaining the Django ORM inside Sanic encapsulating some views and services inside the [asgiref.sync.sync_to_async](https://docs.djangoproject.com/en/4.0/_modules/asgiref/sync/) method - as it's well explained in the [Django documentation](https://docs.djangoproject.com/en/4.0/topics/async/#async-views). And as support, we have a little async Django manager to work with QuerySets asynchronously, but we use it just for little things, and our motivation to have it is to have our views async as much as we can. It is not an ideal scenario, but works for us and as I said is just a migration step before upgrading to Django 4.1.

**Comment by ahopkins** [comment]
Thanks for the information. I did not know about the ORM coming with an async version soon. Progress!



> this is highly unsafe and not recommended on production environments since it leads to data loss

How so? All they are doing is checking if there is a loop. I am not sure that I see how this would lead to data loss.

**Comment by ahopkins** [comment]
Closing this as it is a Django issue.
