### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by mikkab** [sanic-org/sanic-ext#87]
Hi,

Just testing templating module, it looks great, but one feature is terrible, by default autoescape of Jinja2 is ON and lots of symbols is escaped. solution is simple:
app.ext.environment.autoescape = False

I use url_for() function in Flask and it' will be good to add it to templating

Thanks

**Comment by ahopkins** [comment]
Would you be willing to add a PR for that? There are probably more options we should make available as well. Or, in some other way open the api.

**Comment by ahopkins** [comment]
I am going to close this because I am not sure there is functionality change needed for this. The `Environment` object is already exposed:

```py
app.ext.templating.environment.autoescape = False
```

**Comment by ahopkins** [comment]
Happy to entertain other thoughts of API improvements here though.
