### ISSUE TITLE
OpenAPI Class Based Views

### ISSUE THREAD

**Issue by PushUpek** [sanic-org/sanic-ext#88]
How can I use openapi with class based views? Doc section for that is empty.

**Comment by SerGeRybakov** [comment]
For each method of a class-based view you shall add open-api decorators with all the description you need.

You shall not add decorators to the view-class itself.

**Comment by ahopkins** [comment]
Like you would anywhere else.

https://sanic.dev/en/guide/advanced/class-based-views.html#decorators
