### ISSUE TITLE
OpenAPI extension parses dataclass validators as body

### ISSUE THREAD

**Issue by Silur** [sanic-org/sanic-ext#89]
```python
#from pydantic.dataclasses import dataclass
from pydantic.dataclasses import dataclass

@dataclass
class RegisterBody:
    name: str
    email: str
    password: str

    @validator('name')
    def validate_name(cls, v):
        if len(v) < 5:
            raise ValueError('name must be at leasth 5 characters')

@app.post("/register")
@openapi.body({"application/json": RegisterBody})
@validate(json=RegisterBody)
async def register(request, body):
     return json({})
```

The code above produces the OpenAPI `/docs` page to populate a `validator_name` field in the Swagger UI, while for the actual mode it is not a field. Tried with the builting python dataclasses and the Pydantic wrapper too.

![image](https://user-images.githubusercontent.com/3187667/172001173-f0dbb421-3a20-4a2b-9578-9a97a8ade9b3.png)

Sanic v22.3.2
Sanic-ext v22.3.2
Arch Linux x86_64
Python 3.10.4

**Comment by SerGeRybakov** [comment]
Because "schema" is just schema. It's better to have schemas separately from objects with working business logic. You can inherit classes with business logic from schema objects.

**Comment by ahopkins** [comment]
Fix on the way. FYI...

```python
@openapi.body({"application/json": RegisterBody}, validate=True)
```

is the same as 

```python
@openapi.body({"application/json": RegisterBody})
@validate(json=RegisterBody)
```
