### ISSUE TITLE
[Feature Request] OpenAPI support custom openapi file

### ISSUE THREAD

**Issue by XuCcc** [sanic-org/sanic-ext#94]
**Is your feature request related to a problem? Please describe your use case.**

I want to give my `openapi.yaml` to `swagger ui` and find that i can't do this by modify config options([UI | Sanic Framework](https://sanic.dev/en/plugins/sanic-ext/openapi/ui.html#config-options)).

I find in https://github.com/sanic-org/sanic-ext/blob/eb28422b4b274791689aa84ff32d9879139557e5/sanic_ext/extensions/openapi/ui/swagger.html#L25

it only support modify prefix and can't modify suffix `openapi.json`.

**Describe the solution you'd like**

Maybe in  https://github.com/sanic-org/sanic-ext/blob/eb28422b4b274791689aa84ff32d9879139557e5/sanic_ext/extensions/openapi/ui/swagger.html#L25 can be 

`url: "__URL_PREFIX__/__OPENAPI_FILE__",`

And i can set `OAS_OPENAPI_FILE=src/resource/openapi.yaml` to make swagger ui default load my `openapi.yaml` 

**Additional context**

**Comment by ahopkins** [comment]
Solved by #165
