### ISSUE TITLE
[Bug] How to document sanic_jwt routes using swagger?

### ISSUE THREAD

**Issue by GilmarCorreia** [sanic-org/sanic-ext#95]
Hello Sanic Developers. I'm creating an API using sanic_jwt to make a user authentication. I've already documented some custom routes, but I want to write the /auth routes provided by sanic_jwt. Is it possible doing that using an external document? If so, how can I do that?

**Comment by ahopkins** [comment]
You can modify the documentation by manually with:

```python
app.ext.raw({
    "paths": ...
})
```

More specifically, this is an issue for [Sanic JWT](https://github.com/ahopkins/sanic-jwt) that I plan to resolve soon to auto-document those routes. Moving the issue.
